[features]
seeds = false
skip-lint = false
#[programs.localnet]
[programs.devnet]
car_project = "vYwntHTfMyfyzMkc2r5XzmGxuWagLCdb555LfVcukLs"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
wallet = "/Users/aoi/.config/solana/id.json"

[scripts]
test = "node tests/car_project.js"


[test]
startup_wait = 10000
